### PR TITLE
docs: fix some code examples

### PR DESCRIPTION
**Pull request by purarue**

### CODE REVIEW

**Comment by purarue** [comment]
noticed an error and thought I would just copy paste the examples into a nvim buffer and let my lsp correct all the others

**Comment by purarue** [comment]
seems to be mismatch between click types and default due to str-casting:

```
src/bleanser/core/main.py: note: In function "main":
src/bleanser/core/main.py:39:20:39:36: error: Non-overlapping
identity check (left operand type: "Path", right operand type:
"str")  [comparison-overlap]
                assert path2 is _DEFAULT, path2
                       ^~~~~~~~~~~~~~~~~
src/bleanser/core/main.py:47:20:47:40: error: Non-overlapping
identity check (left operand type: "Path", right operand type:
"str")  [comparison-overlap]
                assert path2 is not _DEFAULT
                       ^~~~~~~~~~~~~~~~~~~~~
Found 2 errors in 1 file (checked 56 source files)
```

could `cast(Path, path2)`, or do something else, not sure

**Comment by karlicoss** [comment]
yeah, cast would be fine, thanks!

**Comment by karlicoss** [comment]
huh, interesting, 3.12 macos fails with some unrelated sqlite issue (wonder if the cli output format changed maybe?) -- I'll take a look

**Comment by purarue** [comment]
Yeah I only glanced at it, I thought it might be a issue with ordering so was going to try sorting the results

**Comment by karlicoss** [comment]
Turned out needed and extra pragma for writable `sqlite_master` on some sqlite versions, should be fixed in master https://github.com/karlicoss/bleanser/pull/36

**Pull request merged**
